config/routes.rb
Rails.application.routes.draw do

  get 'pages/solicitartaxi'
  resources :reservations, only: [:new, :create]
  get 'reservations/:id/cancel', controller: :reservations, action: :cancel, as: :cancel_reservation
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'contact', controller: :pages, action: :contact, alias: 'contact'
 get 'about' , controller: :pages, action: :about, alias: 'about'

  devise_for :users
  
  root 'pages#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user ||= User.new
  if user.role == "manager"
   can :manage, :all
  elsif user.role == "seller"
   alias_action :create, :read, :update, :to => :cru
   can :cru, User
  
  end
 
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
end

app/models/favorite_place.rb
class FavoritePlace < ActiveRecord::Base
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  after_initialize :set_default_status
  
  enum status: [:requested, :confirmed, :waiting, :rejected, :dismissed, :cancelled]
  
  def set_default_status

    self.status ||= :requested

  end
  def cancel

    self.status = :cancelled

    self.save

  end
  
  def self.from_user(user)

    Reservation.where(user_id: user.id)

  end

  def self.uncancelled

    Reservation.where.not(status: 5)

  end
end

app/models/taxi.rb
class Taxi < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
       enum role: [:user, :operator, :admin ]
       
       def admin_or_operator?
    self.admin? || self.operator?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
   before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name,:phone ,:email, :password, :current_password, :is_female, :date_of_birth) }
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def solicitartaxi
  end
   def new
    @contact = Contact.new
  end

  private
  
  def contact_params
      params.require(:contact1s).permit(:name, :email,:phone,:message)
    end
  
  end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    
    @reservation = Reservation.new
 
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
 def create

    @reservation = Reservation.new(reservation_params)

    @reservation.user = current_user    respond_to do |format|

      if @reservation.save

        format.html { redirect_to edit_profile_path(current_user.profile), notice: 'Reservation was successfully created.' }

        format.json { render :show, status: :created, location: @reservation }

      else

        format.html { render :new }

        format.json { render json: @reservation.errors, status: :unprocessable_entity }

      end

    end

  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def cancel

    @reservation.cancel

    respond_to do |format|

      format.html { redirect_to edit_profile_path(current_user.profile), notice: 'Reservation was successfully destroyed.' }

      format.json { head :no_content }

    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:reserved_at, :direccion1,:direccion2, :status, :waiting_allowed, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/_menu.html.erb
 <header>
		<nav>
			<ul>
				<li><a href="/"><span class="primero"><i class="icon icon-home2"></i></span>Inicio</a></li>
				<li><a href="/about"><span class="segundo"><i class="icon icon-address-book"></i></span>Acerca de</a>
				<li><a href="/contact"><span class="quinto"><i class="icon icon-mail"></i></span>Contacto</a></li>
				<li><a href="/reservations/new"><span class="cuarto"><i class="incon icon-home2"></i></span>solicitartaxi</a></li>	
				
				<% if user_signed_in? %>
				<li><a href = "/users/edit"  rel = "nofollow"><span class="primero"><i class="icon icon-address-book" >
        </i></span>Profile</a></li>
        <li><a data-method = "delete"  href = '/users/sign_out'  rel = "nofollow"><span class="cuarto"><i class="icon icon-users" ></i></span>Cerrar sesión</a></li>
        
        
				<% else %>
			
				<li><a href="/users/sign_in"><span class="cuarto"><i class="icon icon-users"></i></span>Inicio Sessión</a></li>
				<li><a href="/users/sign_up"><span class="cuarto"><i class="icon icon-users"></i></span>Crear Cuenta</a></li>
				<%end%>
			</ul>
		</nav>
	</header>
	
	

app/views/layouts/_menu2.html.erb
 <header>
		<nav>
			<ul>
				<li><a href="/"><span class="primero"><i class="icon icon-home2"></i></span>Inicio</a></li>
				<li><a href="/about"><span class="segundo"><i class="icon icon-address-book"></i></span>Acerca de</a>
				<li><a href="/contact"><span class="quinto"><i class="icon icon-mail"></i></span>Contacto</a></li>
				
				<% if user_signed_in? %>
				<li><a href="#"><span class="tercero"><i class="icon icon-road"></i></span>Servicios Pendientes</a></li>
				<li><a href="#"><span class="tercero"><i class="icon icon-road"></i></span>Listar mis servicios encuestados</a></li>
				
               <li><a data-method = "delete"  href = '/users/sign_out'  rel = "nofollow"><span class="cuarto"><i class="icon icon-users" ></i></span>Cerrar sesión</a></li>
                
        
				<% else %>
				<li><a href="/users/sign_in"><span class="cuarto"><i class="icon icon-users"></i></span>Inicio Sessión</a></li>
				<li><a href="/users/sign_up"><span class="cuarto"><i class="icon icon-users"></i></span>Crear Cuenta</a></li>
				<%end%>
			</ul>
		</nav>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyecto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body background="fondo.png">

 <h1 id ="Text">Taxi-Express</h1>
  <%= render 'layouts/menu' %>
  
   
	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
	<%= yield %>

</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyecto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <h1 id ="Text">Taxi-Express</h1>
  <%= render 'layouts/menu' %>
   
	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
	<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<section >
<div id= 'text3'>
<h1>Sobre Nosotros</h1>
</div>


<div id='info'>
    <p>Taxi-Express es la Web de solicitud de taxis más usada en el pais. La aplicación conecta</p>
    <p>a los usuarios pasajeros y usuarios conductores, de forma fácil, rápida y segura. Taxi-</p>
    <p>Express está disponible para tablet, pc y celulares</p>
    <br>


    <br />
    
</div>
</section>

<section >
<div id='text3'>
<h1>Nuestra historia</h1>
</div>

<div id='info'>
    <p>Lanzada en Enero de 2015, la idea de la aplicación surgio en el 2014. Después de eso,</p>
    <p>Taxi-Express se convirtió en el pionero en servicios de geolocalización vía aplicación </p>
    <p>en Perú. Actualmente disponible en todas la ciudades del pais, Taxi-Express ha</p>
    <p> el servicio de solicitud de taxis.</p>
</div>
</section>

app/views/pages/contact.html.erb
<div id='text3'>
<h1>CONTACTO</h1>
    <p>¿Tienes dudas, sugerencias, elogios o críticas? Contacta nuestro servicio de atención al cliente en Perú por teléfono o correo.</p>
</div>

<div id='info'>
    
   <p>Atención al usuario: 01564613</p>
   <p>contact@taxiexpress.com.pe</p>
   <p>Av. La marina 1650 San Miguel</p>
</div>

<div class="contenedor-formulario">
<div class="wrap">

<from action="contact" class="formulario" name="formulario_s" method="get">
  <div>
      <div class="input-group">
    <input type='text' id="nombre" name="nombre"> 
   <label class="label " for='nombre'>Tu Nombre:</label>
   
   </div>
   <div class="input-group">
   <input type="email" id='correo'name='correo' >
    <label class="label" for='correo'>Tu e-mail:</label>
   
   </div>
   <div class="input-group">
    <input type='text' id='telefono'name='telefono'  >
   <label class= "label" for='telefono'>Télefono:</label>
   
   </div>
   <div class="input-group">
    <textarea type='text'  id='mensaje' name='mensaje' style="padding: 6px 12px;" cols="40 " rows="9"></textarea>
   <label class="label" for='mensaje'>Mensaje:</label>
   
   </div>
   <input type="submit" id="btn-submit" value="Enviar">
 </div> 
</from>
    <br>


    <br />
</div>
</div>

<div align="center"> 

<iframe 
width="600" 
height="450" 
frameborder="0" 
style="border:0" 
src="https://www.google.com/maps/embed/v1/place?q=place_id:EitBdi4gTGEgTWFyaW5hIDE2NTAsIFNhbiBNaWd1ZWwgMTUwODcsIFBlcsO6&key=AIzaSyBv4ca4UjFuq6NFm1A2g_sU0DiiiSLrN9A" allowfullscreen>
</iframe>

</div>


    

app/views/pages/index.html.erb
<div id= 'text3'>

<h1>Taxi-Express tu taxi seguro</h1>
 <br>    <br />
<h2> ¡Califica a tu conductor y ay&uacute;danos a premiar el buen servicio!</h2>
</div>
<video widtg="640" height="360"  autoplay preload="auto">
    <source src="video.mp4" type='video/mp4'/>
    
</video>

app/views/pages/solicitartaxi.html.erb
<div class="form_top">
<h1>Buscas un Taxi!</h1><br>


     <input class="input_blanco input input_default input_form_bottom error" 
            name="desde_hasta" id="desde_hasta" type=
            "text" value="Rec&oacute;geme de:Calle, Distrito">
                    
   </div>
   
    <input class="input_blanco input input_default input_form_bottom error" 
           name="hasta_desde" id="hasta_desde" type=
           "text" value="Ll&eacute;vame a: Calle, Distrito"> 
    </div>
  
  <div class="contenedor-formulario">
<div class="wrap">

<from action="" class="formulario" name="formulario_s" method="get">
  <div>
      <div class="input-group">
    <input type='text' id="nombre" name="nombre"> 
   <label class="label " for='nombre'>Nombre y Apellidos:                        </label>
   
  
   </div>
   <div class="input-group">
    <input type='text' id='telefono'name='telefono'  >
   <label class= "label" for='telefono'>Télefono:</label>
   
   </div>
   <input type="submit" id="btn-submit" value="Enviar">
 </div>  
</from>
 


                    
                   

app/views/reservations/_for_current_user.html.erb
<%- model_class = Reservation -%>

<div class="page-header">

  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>

</div><table class="table table-striped">

  <thead>

    <tr>

      <th><%= model_class.human_attribute_name(:id) %></th>

      <th><%= model_class.human_attribute_name(:reserved_at) %></th>

      <th><%= model_class.human_attribute_name(:seats) %></th>

      <th><%= model_class.human_attribute_name(:status) %></th>

      <th><%= model_class.human_attribute_name(:waiting_allowed) %></th>

      <th><%= model_class.human_attribute_name(:created_at) %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>

    </tr>

  </thead>

  <tbody>

    <% Reservation.from_user(current_user).uncancelled.each do |reservation| %>

      <tr>

        <td><%= link_to reservation.id, reservation_path(reservation) %></td>

        <td><%= reservation.reserved_at %></td>

        <td><%= reservation.seats %></td>

        <td><%= reservation.status.titleize %></td>

        <td><%= reservation.waiting_allowed %></td>

       <td><%=l reservation.created_at %></td>

        <td>

          <%= link_to t('.destroy', :default => 'Cancel'), cancel_reservation_path(reservation),  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger' %>

        </td>

      </tr>

    <% end %>

  </tbody>

</table>
<%= link_to t('.new', :default => t("helpers.links.new")), new_reservation_path, :class => 'btn btn-primary' %>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reserved_at %><br>
    <%= f.datetime_select :reserved_at %>
  </div>
  <div class="field">
    <%= f.label :direccion1 %><br>
    <%= f.text_field :direccion1 %>
  </div>
  <div class="field">
    <%= f.label :direccion2 %><br>
    <%= f.text_field :direccion2 %>
  </div>
   <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  
  <div class="field">
    <%= f.label :waiting_allowed %><br>
    <%= f.check_box :waiting_allowed %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Reserved at</th>
      <th>Seats</th>
      <th>Status</th>
      <th>Waiting allowed</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.reserved_at %></td>
        <td><%= reservation.seats %></td>
        <td><%= reservation.status %></td>
        <td><%= reservation.waiting_allowed %></td>
        <td><%= reservation.user %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reserved at:</strong>
  <%= @reservation.reserved_at %>
</p>

<p>
  <strong>Seats:</strong>
  <%= @reservation.seats %>
</p>

<p>
  <strong>Status:</strong>
  <%= @reservation.status %>
</p>

<p>
  <strong>Waiting allowed:</strong>
  <%= @reservation.waiting_allowed %>
</p>

<p>
  <strong>User:</strong>
  <%= @reservation.user %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>